const BASE_REGEN_DELAY = 6;
const BASE_LOS = 6;
const BASE_REGEN = 0.5;

const STARTING_HUNGER = 500;
const STARTING_THIRST = 500;

export {
  BASE_REGEN_DELAY,
  BASE_LOS,
  BASE_REGEN,
  STARTING_HUNGER,
  STARTING_THIRST
}